title: URAの博物誌
description: >
    大学での研究開発マネジメントや産学連携、PURなどについて書いています。
url: "https://tokiwatch.github.io"
# email: tokiwatch@gmail.com
timezone: Asia/Tokyo
encoding: utf-8
twitter_username: tokiwatch
github_username:  tokiwatch

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
lsi: true

